copy_jab_exps( ...
    '/nrs/branson/kwaki/jab_experiments/M173VGATXChR2_base', ...
    '/groups/branson/bransonlab/kwaki/forRutuja/', ...
    '/nrs/branson/kwaki/jab_experiments/M173VGATXChR2_base/M173_20150423.jab' ...
);

% '/nrs/branson/kwaki/jab_experiments/M173VGATXChR2_base'